### ISSUE TITLE
V4 Release

### ISSUE THREAD

**Issue by s-yadav** [s-yadav/react-number-format#231]
- [x] Support defaultValue
- [x] Trigger onValueChange if the value is formatted due to prop change. #227
- [x] Add password as valid type. #206
- [x] Support indian (lakh) and chinese (wan) style thousand grouping. #184
- [x] Always allow . to be typed as decimal separator, even decimal separator is defined differently (Lot of ask for this feature) #133, #162, #168, #223, #115
- [ ] ~~Support a pre evaluate to modify values. #205~~ Keeping this out of scope of v4 as it is bringing lot of complexity around caret position.

**Comment by s-yadav** [comment]
Released v4

**Comment by cmsandiga** [comment]
#168, still open, this PR will be merged?

**Comment by s-yadav** [comment]
That is implemented in a different way for support of typing `.` and which will be treated as defined decimal separator. 
On V4 there will be no need of defining multiple decimal separators. Will close that PR.

**Comment by cmsandiga** [comment]
This works in both ways?, because in our case, we would like that when user digit `,` this will be replace with  `.`. We were trying to use in that way but it no works for us.
