### ISSUE TITLE
v3 Tracker

### ISSUE THREAD

**Issue by s-yadav** [s-yadav/react-number-format#99]
- [x] Refactor code for better stability
- [x] Fix Issue with formatting and caret position in android chrome browser. #88
- [x] Support numbers in  prefix /suffix . Fix for  #73
- [x] Support phone number formatting and numbers in format. Fix for #81
- [x] Add flowtype check
- [x] Upgrade to react 16 and enzyme 3.0
- [x] Fix caret position when custom formatting is applied #97
- [x] More accurate unit testing by simulating key inputs / focus and mouse events.
- [x] Add a custom render method as props for displaying formatted value as text #86
- [x] Add dynamic masking #83
- [x] Standardize what can come as value props so plugin can make better assumption about formatting. #82 
- [x] Keep caret position withing typable area. #82 , #85 
- [x] Fix preceding zero removal bug. #96 
- [x] Fix incorrect behaviour when precision enabled and 0 with precision #70 
- [x] Make decimal scale fixed 0s optional #48 
- [x] Correct caret position on focus. Fixed #112, #85
- [x] Correct intermediate input on blur event. Fixed #96
- [x] Write migration doc from v2 to v3

**Comment by bmulcahy** [comment]
I am getting this error with react-number-format@3.0.0-alpha

ERROR in ./~/react-number-format/lib/number_format.js
Module not found: Error: Can't resolve './utils' in 'D:\Projects\esd_upload\node_modules\react-number-format\lib'
 @ ./~/react-number-format/lib/number_format.js 15:13-31


looks like it is looking for utils in ./lib but it is found in ./src

**Comment by s-yadav** [comment]
@bmulcahy pushed fix in 3.0.0-alpha2

**Comment by bmulcahy** [comment]
thanks I moved its own thread so you can keep track of it like the previous ones. I appreciate the quick work!

**Comment by pandaiolo** [comment]
@s-yadav is pushing a new npm version possible, to include #111 ?

**Comment by s-yadav** [comment]
@pandaiolo I am planning to release v3.0.0 by EOD as all checklist are done. That will incorporate all the fixes.

**Comment by s-yadav** [comment]
V3 Released.
